### ISSUE TITLE
Rename `master` with `Built-In Node`

### ISSUE THREAD

**Issue by uhafner** [jenkins-docs/quickstart-tutorials#394]
It would make sense to rename the controller to `Built-In Node`. 

In the screenshot you see my Docker based configuration on the top and your configuration on the button. I must admit that I don't understand where this text is coming from as I did not actually change it in my configuration.

![Bildschirmfoto 2024-07-02 um 10 53 30](https://github.com/jenkins-docs/quickstart-tutorials/assets/503338/8566167e-170e-4abb-b34d-1ddbe950d168)

**Comment by uhafner** [comment]
Or is this text coming from the translations?

**Comment by gounthar** [comment]
There is no reference to `master` in the code base. 🤔

**Comment by uhafner** [comment]
Maybe this is related to the localization? I normally use the locale plugin to set up English. I did not do this in the quickstart example.

**Comment by uhafner** [comment]
Indeed, when I switch to English, the correct term is shown. When I switch to German, the *English* word master is shown 🙈.

**Comment by gounthar** [comment]
Okay, let me add the locale plugin in the install.

**Comment by uhafner** [comment]
FTR: https://github.com/jenkinsci/jenkins/pull/9434

**Comment by gounthar** [comment]
Thanks, Ulli! 👍
